# Generated by Django 5.2.1 on 2025-06-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='name',
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default='admin', max_length=128),
        ),
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(default='admin', max_length=100, unique=True),
        ),
    ]
